### PR TITLE
allow readonly property to change

### PR DESCRIPTION
**Pull request by malko**
I propose a little change to allow the readOnly attribute to be an expression and to eventually changing over time.

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
Why do you use a function and watcher instead of using the two-way data-binding via the usage of ordinary scope-variable declared in the directive scope with =? ?

**Comment by malko** [comment]
cause i need an expression to be there, but a 2 way binding could be sufficient, i can manage it in the upper controller.

**Comment by KillerCodeMonkey** [comment]
Correclty and it would be faster because you save a watcher
Am 17.07.2015 17:19 schrieb "Jonathan Gotti" <notifications@github.com>:

**Comment by malko** [comment]
thinking about it again, we will have something like that with a ```=?```:
```js
                  if ($scope.readOnly) {
                        $scope.$watch('readOnly', function (readOnly) {
                            editor.editor[readOnly ? 'disable' : 'enable']();
                        });
                    }
```
So the watcher will still be needed and we don't really need a two way data binding in this case.
Actually using 2 way data binding will add one more watcher than expression.
Using an expression is basically how ng-readonly works.
What do you think?

**Comment by KillerCodeMonkey** [comment]
it is okay.
But keep in mind you could do the whole thing without that whole stuff.
If the editor is created you can get the instance via the editorCreated-event -> you can manipulate the editor directly in your instance.

I added the readonly flag only if you know you do not need to enable the editor later.
Like you have different authorization roles and some can edit the whole thing, or after you have saved some stuff you are not able to edit it again.

So your last word, before i merge ;) ????

**Comment by malko** [comment]
In our application the editable state changes over time and it seems more practical to do it that way.
So our last word is Yeah ;)

**Comment by KillerCodeMonkey** [comment]
check

**Comment by KillerCodeMonkey** [comment]
new release tag 1.0.9 --> available over bower

**Comment by malko** [comment]
thanks

**Comment by khashayar** [comment]
Can someone please clarify why `readOnly` should be a function and not simply a scope variable?

BTW, the readOnly change broke my application on live environment. Could you please consider a minor version bump instead of patch in case of breaking changes?

**Comment by KillerCodeMonkey** [comment]
The ordinary readonly Attribute takes an expression to evaluate. Making
minor releases is a good approach.

Like i wrote in earlier comment. For me it is the same if the Attribute is
ordinary two way data binding or function call or boolean string.

**Pull request merged**
