### PR TITLE
Added new `save` option

### PR DESCRIPTION
**Pull request by fracmak**
This option specifies whether we want to get/save html, raw text, or contents of the text editor.

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
@fracmak 
thanks for improving ngquill. It is really nice to see how many people use/improve that little piece of code.

Might you implement a check of allowed formats or is there a fallback in quilljs?

**Comment by fracmak** [comment]
What would you like to have happen if you provide an invalid format? Throwing an error? We could always fall back to 'html' if you put in an invalid format. Either way works for me.

**Comment by KillerCodeMonkey** [comment]
fallback to standard html would be fine i think :+1:

**Comment by fracmak** [comment]
done, pull request updated

**Comment by fracmak** [comment]
awesome, thanks! :100:

**Comment by KillerCodeMonkey** [comment]
Nothing you have to thank for ;). I have to thank you and thats how open
source works :)

**Pull request merged**
